spring:
  application:
    name: cooperApp-notificacion-service
  kafka:
    bootstrap-servers: kafka:29092  # Cambió de localhost:9092
    consumer:
      group-id: reactive-notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.pe.fisi.sw.cooperApp.cooperApp_notificacion_service.dto.NotificationEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        spring.json.value.default.type: com.pe.fisi.sw.cooperApp.cooperApp_notificacion_service.dto.NotificationEvent

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka  # Cambió de localhost
  instance:
    hostname: notificacion-service  # Cambió de localhost
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: false  # Cambió a false para usar hostname
    non-secure-port: 8090
    home-page-url: http://notificacion-service:8090/  # Cambió hostname
    status-page-url: http://notificacion-service:8090/actuator/info
    health-check-url: http://notificacion-service:8090/actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always