# CooperApp Gateway
spring:
  config:
    import: optional:configserver:http://cooperapp-cloudserver:8888  # Cambió de localhost
  application:
    name: cooperApp-gateway
  cloud:
    config:
      uri: http://cooperapp-cloudserver:8888  # Cambió de localhost
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: cooperApp
          uri: lb://cooperApp
          predicates:
            - Path=/v1/auth/**,/v1/accounts/**
          filters:
            - StripPrefix=0
            - PreserveHostHeader
        - id: cooperApp-notificacion-service
          uri: lb://cooperApp-notificacion-service
          predicates:
            - Path=/v1/notifications/**
          filters:
            - StripPrefix=0
            - PreserveHostHeader

server:
  port: 8222

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka  # Cambió de localhost
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: gateway  # Cambió de localhost
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: false  # Cambió a false para usar hostname
    non-secure-port: 8222
    home-page-url: http://gateway:8222/  # Cambió hostname

# Configuración de actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      access: unrestricted

# Logging para debug (opcional)
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG