## cooperApp Cloud Config
server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: cooperApp-cloud
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations