#CooperApp Discovery
# CooperApp Discovery
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: cooperApp-discovery
  cloud:
    config:
      fail-fast: true

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

